export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL'
export const EMPTY_CART = 'EMPTY_CART'
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
